### PR TITLE
feat(pulumi): Support `--yes` and `--skipPreview` options

### LINKED ISSUE #142: Pulumi: Running up with --yes or --skip-preview
Getting the following issue when running `nx run-many -t up` in my project through GitHub Actions:

```
error: --yes or --skip-preview must be passed in to proceed when running in non-interactive mode
```

How can I pass this argument in to `pulumi up`? I think it should either be default, or an option.

### PR DESCRIPTION
**Pull request by ffMathy**
Fixes #142.

Marked as draft, as I am not sure how to test it. If you think it's okay to merge without testing, let me know.

### CODE REVIEW

**Comment by TriPSs** [comment]
Thanks for the PR, looks good as is. 

One thing, please do use conventional commits as these changes (like the previous) will now not show up the changelog.

**Comment by ffMathy** [comment]
Interesting. What are "conventional commits"? Never heard of that before actually.

**Comment by TriPSs** [comment]
I see I'm also missing the contributing here 😅, here you can find more info: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ffMathy** [comment]
Oh, interesting! That's cool. I'll definitely start using that myself. What can we do about the existing commits though? I'm not a GIT mastermind.

Perhaps we could squash the pull request when we merge it, and then set a commit message there?

**Comment by TriPSs** [comment]
Bit of a shame that the changelog still did not pick it up 😅 Maybe it has to do with the fact that it was a merge commit 🤔

**Comment by ffMathy** [comment]
Yeah maybe it should have been a squash. Hard to tell.

Thanks for teaching me about conventional commits though!

**Pull request merged**
