### PR TITLE
fix: forgot to add to executors

### PR DESCRIPTION
**Pull request by ffMathy**

### CODE REVIEW

**Comment by ffMathy** [comment]
@TriPSs thanks for merging this - can we bump the version to make a release? How do I do that?

**Comment by TriPSs** [comment]
Think we need to make a PR that bumped the version one, forgot that this happends when I merge quickly after after each other.

**Comment by ffMathy** [comment]
Okay. How do we do that?

**Comment by TriPSs** [comment]
Checkout master, bump version to 3.4.0, make PR :)

**Pull request merged**
